repositoryUrl: https://github.com/dynamsoft-docs/camera-enhancer-docs/blob/main
repository: dynamsoft-docs/camera-enhancer-docs
docFullPath: https://www.dynamsoft.com/camera-enhancer/docs/core/
firstLevelUrl: /camera-enhancer/docs/core
docHomePage: /camera-enhancer/docs/core/introduction/

productUrl: https://www.dynamsoft.com/camera-enhancer/overview/
productName: Dynamsoft Camera Enhancer

introduction: /camera-enhancer/docs/core/introduction/
programming: /camera-enhancer/docs/core/programming/
parameters: /camera-enhancer/docs/core/parameters/
license_activation: /camera-enhancer/docs/core/license-activation/
release_notes: /camera-enhancer/docs/core/release-notes/
parameter-reference: /camera-enhancer/docs/core/parameters/reference/
faq: /camera-enhancer/docs/core/faq/

ios: /camera-enhancer/docs/mobile/programming/ios/

android: /camera-enhancer/docs/mobile/programming/android/

js: /camera-enhancer/docs/web/programming/javascript/
js-rn: /camera-enhancer/docs/web/programming/javascript/release-note/

flutter: /capture-vision/docs/mobile/programming/flutter/

xamarin: /capture-vision/docs/mobile/programming/xamarin/

cordova: /capture-vision/docs/mobile/programming/cordova/

react_native: /capture-vision/docs/mobile/programming/react-native/

reference: /camera-enhancer/docs/core/parameters/reference/
enumerations: /camera-enhancer/docs/core/parameters/enumerations/
mobile-enum: /camera-enhancer/docs/core/programming/enumerations/

license-error: /camera-enhancer/docs/core/faq/license-error/
contact-us: /camera-enhancer/docs/core/faq/contact-us/
gallery: /camera-enhancer/docs/core/resources/code-gallery/
all-release-note: /camera-enhancer/docs/core/release-notes/
resource: /camera-enhancer/docs/core/resources/

barcode-deploy-ios: /barcode-reader/programming/ios/api-reference/camera-enhancer/
barcode-deploy-android: /barcode-reader/programming/android/api-reference/camera-enhancer/
barcode-enum: /barcode-reader/parameters/enum/

assets: /camera-enhancer/docs/core/assets/
edit_icon: /camera-enhancer/docs/core/assets/img-icon/edit-icon.png
smile_icon: /camera-enhancer/docs/core/assets/img-icon/icon-smile.png
sad_icon: /camera-enhancer/docs/core/assets/img-icon/icon-sad.png
dbr_icon: /camera-enhancer/docs/core/assets/img-icon/icon-dbr.svg
dwt_icon: /camera-enhancer/docs/core/assets/img-icon/icon-dwt.svg
dnt_icon: /camera-enhancer/docs/core/assets/img-icon/icon-dnt.svg

overview: /camera-enhancer/overview/
download: /camera-enhancer/downloads/

useVersionTree: true

baseurl: "/camera-enhancer/docs/core"
plugins:
  - jemoji
  - jekyll-sitemap

edition: algorithm

defaults:
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/flutter"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/xamarin"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/cordova"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/react-native"
    values:
      category: "mobile-repo"
      edition: "mobile"

url: "https://www.dynamsoft.com" # sitemap root
